# Lab 9 - Introduction to Python ETL Processes and Data Integration
Objective: Use Python and pandas to integrate datasets into a unified dataframe. This lab focuses on the practical application of data integration techniques to prepare a comprehensive dataset for analysis.

## Importing libraries

In [2]:
import pandas as pd

## Task 1: Explore Individual Datasets

In [3]:
cust = pd.read_csv("Global Superstore 3NF/Customers.csv")
order = pd.read_csv("Global Superstore 3NF/Orders.csv")
prod = pd.read_csv("Global Superstore 3NF/Products.csv")

### Key Columns
The key columns that link the data sets are Customer ID, Order ID and Product ID; the data can be integrated with these columns.

In [12]:
cust.head()

  Customer ID     Customer Name           City            State        Country
0    RH-19495       Rick Hansen  New York City         New York  United States
1    JR-16210     Justin Ritter     Wollongong  New South Wales      Australia
2    CR-12730      Craig Reiter       Brisbane       Queensland      Australia
3    KM-16375  Katherine Murray         Berlin           Berlin        Germany
4     RH-9495       Rick Hansen          Dakar            Dakar        Senegal

In [5]:
order.head()

,Row ID,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Postal Code,Market,Region,Quantity,Sales,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,RH-19495,TEC-AC-10003033,7/31/12 12:34,7/31/12 8:35,Same Day,Consumer,10024.0,US,East,7,2309.650,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,JR-16210,FUR-CH-10003950,2/5/13 12:09,2/7/13 14:37,Second Class,Corporate,NaN,APAC,Oceania,9,3709.395,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,CR-12730,TEC-PH-10004664,10/17/13 16:09,10/18/13 12:08,First Class,Consumer,NaN,APAC,Oceania,9,5175.171,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,KM-16375,TEC-PH-10004583,1/28/13 9:08,1/30/13 15:08,First Class,Home Office,NaN,EU,Central,5,2892.510,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,RH-9495,TEC-SHA-10000501,11/5/13 15:54,11/6/13 8:13,Same Day,Consumer,NaN,Africa,Africa,8,2832.960,0.0,311.5200,903.04,Critical

In [6]:
prod.head()

,Product ID,Category,Sub-Category,Product Name
0,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...
1,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black"
2,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID"
3,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless"
4,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed"

### Data Quality Issues
The ID column names are consistent across the data sets. The ID data types are also consistent - all objects. 

There are fewer unique IDs than there are total rows for every dataset. Since these IDs are not actually valid (unique) keys, the data sets need to be cut down so the IDs are unique before joining on them.

In [8]:
cust.info()
cust.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24959 entries, 0 to 24958
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer ID    24959 non-null  object
 1   Customer Name  24959 non-null  object
 2   City           24959 non-null  object
 3   State          24959 non-null  object
 4   Country        24959 non-null  object
dtypes: object(5)
memory usage: 975.1+ KB

       Customer ID Customer Name           City       State        Country
count        24959         24959          24959       24959          24959
unique        1590           795           3636        1094            147
top       PO-18850   Frank Olsen  New York City  California  United States
freq            40            47            355         900           4688

In [9]:
order.info()
order.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Customer ID     51290 non-null  object
 3   Product ID      51290 non-null  object
 4   Order Date      51290 non-null  object
 5   Ship Date       51290 non-null  object
 6   Ship Mode       51290 non-null  object
 7   Segment         51290 non-null  object
 8   Postal Code     9994 non-null   float64
 9   Market          51290 non-null  object
 10  Region          51290 non-null  object
 11  Quantity        51290 non-null  int64
 12  Sales           51290 non-null  float64
 13  Discount        51290 non-null  float64
 14  Profit          51290 non-null  float64
 15  Shipping Cost   51290 non-null  float64
 16  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(10)
memory usage: 6.7+ MB

,Row ID,Postal Code,Quantity,Sales,Discount,Profit,Shipping Cost
count,51290.00000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.50000,55190.379428,3.476545,246.490581,0.142908,28.610982,26.375915
std,14806.29199,32063.693350,2.278766,487.565361,0.212280,174.340972,57.296804
min,1.00000,1040.000000,1.000000,0.444000,0.000000,-6599.978000,0.000000
25%,12823.25000,23223.000000,2.000000,30.758625,0.000000,0.000000,2.610000
50%,25645.50000,56430.500000,3.000000,85.053000,0.000000,9.240000,7.790000
75%,38467.75000,90008.000000,5.000000,251.053200,0.200000,36.810000,24.450000
max,51290.00000,99301.000000,14.000000,22638.480000,0.850000,8399.976000,933.570000

In [13]:
order.describe(include='object')

,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Market,Region,Order Priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25035,1590,10292,48971,49231,4,3,7,13,4
top,CA-2014-100111,PO-18850,OFF-AR-10003651,9/13/13 14:42,8/4/14 9:45,Standard Class,Consumer,APAC,Central,Medium
freq,14,97,35,4,4,30775,26518,11002,11117,29433

In [10]:
prod.info()
prod.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10768 entries, 0 to 10767
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product ID    10768 non-null  object
 1   Category      10768 non-null  object
 2   Sub-Category  10768 non-null  object
 3   Product Name  10768 non-null  object
dtypes: object(4)
memory usage: 336.6+ KB

             Product ID         Category Sub-Category Product Name
count             10768            10768        10768        10768
unique            10292                3           17         3788
top     OFF-PA-10004673  Office Supplies        Paper      Staples
freq                  4             5955          825           46

## Task 2: Data Preparation

### Deduplicating IDs

In [16]:
cust_dedup = cust.drop_duplicates(subset=['Customer ID'])

In [17]:
cust_dedup.describe()

       Customer ID  Customer Name           City    State        Country
count         1590           1590           1590     1590           1590
unique        1590            795            860      536            122
top       ZC-11910  Thais Sissman  New York City  England  United States
freq             1              2             28       35            173

In [18]:
order_dedup = order.drop_duplicates(subset=['Order ID'])

In [20]:
order_dedup.describe(include='object')

,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Market,Region,Order Priority
count,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035
unique,25035,1589,8815,24467,24523,4,3,7,13,4
top,MX-2012-134460,PO-18850,OFF-BI-10004632,8/8/13 12:48,8/13/11 15:42,Standard Class,Consumer,APAC,Central,Medium
freq,1,40,16,3,3,14953,12916,5437,5237,14281

In [21]:
prod_dedup = prod.drop_duplicates(subset=['Product ID'])

In [22]:
prod_dedup.describe(include='object')

             Product ID         Category Sub-Category Product Name
count             10292            10292        10292        10292
unique            10292                3           17         3660
top     OFF-AP-10002203  Office Supplies        Paper      Staples
freq                  1             5689          781           45

## Task 3: Data Integration

### Merge Orders with Products

First, merging on the data without deduplication. See how the total number of Order IDs actually increases because of the duplicate order-product ID pairs.

In [28]:
order_prod_dup_merge = pd.merge(order, prod, on='Product ID')

In [29]:
order_prod_dup_merge.describe(include='object')

,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Market,Region,Order Priority,Category,Sub-Category,Product Name
count,55996,55996,55996,55996,55996,55996,55996,55996,55996,55996,55996,55996,55996
unique,25035,1590,10292,48971,49231,4,3,7,13,4,3,17,3788
top,IN-2013-42311,BE-11335,OFF-AR-10003651,6/29/12 10:51,9/14/13 12:08,Standard Class,Consumer,APAC,Central,Medium,Office Supplies,Binders,Staples
freq,16,107,105,5,5,33611,29005,12113,12404,32127,34170,6825,234

Now with the deduplicated data:

In [32]:
order_prod_merge = pd.merge(order_dedup, prod_dedup, on='Product ID')

In [33]:
order_prod_merge.describe(include='object')

,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Market,Region,Order Priority,Category,Sub-Category,Product Name
count,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035
unique,25035,1589,8815,24467,24523,4,3,7,13,4,3,17,3490
top,MX-2012-134460,PO-18850,OFF-BI-10004632,8/8/13 12:48,8/13/11 15:42,Standard Class,Consumer,APAC,Central,Medium,Office Supplies,Storage,Staples
freq,1,40,16,3,3,14953,12916,5437,5237,14281,12627,2649,88

### Concat vs Merge of Order-Product Table with the Customers table

In [38]:
order_prod_cust_merge = pd.merge(order_prod_merge, cust_dedup, on='Customer ID')

In [39]:
order_prod_cust_merge.describe(include='object')

,Order ID,Customer ID,Product ID,Order Date,Ship Date,Ship Mode,Segment,Market,Region,Order Priority,Category,Sub-Category,Product Name,Customer Name,City,State,Country
count,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035,25035
unique,25035,1589,8815,24467,24523,4,3,7,13,4,3,17,3490,795,859,536,122
top,MX-2012-134460,PO-18850,OFF-BI-10004632,8/8/13 12:48,8/13/11 15:42,Standard Class,Consumer,APAC,Central,Medium,Office Supplies,Storage,Staples,Frank Olsen,New York City,England,United States
freq,1,40,16,3,3,14953,12916,5437,5237,14281,12627,2649,88,46,758,884,4480

## Task 4: Post-Integration Review

## Challenges